language: android
jdk: oraclejdk7
android:
  components:
    - build-tools-23.0.0
    - extra-android-support
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
  - chmod +x gradlew

script:
  ./gradlew clean build
