anguage: android
jdk: oraclejdk7
android:
  components:
    - build-tools-22.0.1
    - extra-android-support
    - android-22
    - extra-google-m2repository
    - extra-android-m2repository
      #    - sys-img-x86-android-19